version: "3"

services:
  app:
    container_name: webhook-node
    restart: always
    build: .
    ports: 
      - "1337:1337"
    command: npm start
    env_file:
     - ./api.env
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
